version: '3.1'

services:

  web:
    image: nginx
    restart: always
    volumes:
        - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx_conf/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
        - front

  site1:
    image: wordpress:4.9.5-php7.0-apache
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_TABLE_PREFIX: site1_
    networks:
        - front
        - back
    volumes:
        - site1_content:/var/www/html/wp-content

  site2:
    image: wordpress:4.9.5-php7.0-apache
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_TABLE_PREFIX: site2_
    networks:
        - front
        - back
    volumes:
        - site2_content:/var/www/html/wp-content

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
        - back
    volumes:
        - db_data:/var/lib/mysql


networks:
    front:
    back:

volumes:
    site1_content:
    site2_content:
    db_data:
